mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zbw.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8000

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs

spring:
  # 用户名 密码 需要根据实际情况修改
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  resources:
    chain:
      cache: true